27 окт. 2022 15:11:12,672 ERROR LogicsModule - lsfusion.gwt.client.base.exception.RemoteRetryException no such object in table at '27.10.2022, 15:11' from '127.0.0.1 - web': 
null
	at java.lang.Throwable.Throwable(Throwable.java:63)
	at java.lang.Exception.Exception(Exception.java:25)
	at net.customware.gwt.dispatch.shared.DispatchException.DispatchException(DispatchException.java:15)
	at lsfusion.gwt.client.base.exception.RemoteRetryException.RemoteRetryException(RemoteRetryException.java:8)
	at lsfusion.gwt.client.base.exception.RemoteRetryException_FieldSerializer.instantiate(RemoteRetryException_FieldSerializer.java:17)
	at com.google.gwt.user.client.rpc.impl.SerializerBase$MethodMap.$instantiate(SerializerBase.java:55)
	at com.google.gwt.user.client.rpc.impl.SerializerBase.$instantiate(SerializerBase.java:112)
	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamReader.$readObject(ClientSerializationStreamReader.java:129)
	at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.onResponseReceived(RequestCallbackAdapter.java:216)
	at com.google.gwt.http.client.Request.$fireOnResponseReceived(Request.java:250)
	at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:412)
	at Unknown.anonymous(XMLHttpRequest.java:329)
	at com.google.gwt.core.client.impl.Impl.apply(Impl.java:309)
	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:361)
	at Unknown.anonymous(Impl.java:78)

